# Generated by Django 6.0.4 on 2026-05-05 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_productstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockin',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockout',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.size')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stock',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_outs', to='inventory.productvariant'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='inventory.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('variant', 'store')},
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
    ]
